#######################################################
#        ____  __                __                   #
#       / __ \/ /_  ____ _____  / /_____  ____ ___    #
#      / /_/ / __ \/ __ `/ __ \/ __/ __ \/ __ `__ \   #
#     / ____/ / / / /_/ / / / / /_/ /_/ / / / / / /   #
#  _ /_/   /_/ /_/\__,_/_/ /_/\__/\____/_/ /_/_/_/    #
# | |     / /___ ___  ______  ____  (_)___  / /______ #
# | | /| / / __ `/ / / / __ \/ __ \/ / __ \/ __/ ___/ #
# | |/ |/ / /_/ / /_/ / /_/ / /_/ / / / / / /_(__  )  #
# |__/|__/\__,_/\__, / .___/\____/_/_/ /_/\__/____/   #
#              /____/_/                               #
#######################################################


###### WAYPOINT TELEPORT CONFIG ######

AutoSave: 30
# ^ How often should the plugin save data from memory to file? In minutes.

ExpCost: 0
# ^ How many levels teleporting should cost. In levels.

Tag: Phantom-Waypoints
# ^ The tag that should be placed infront of the messages in chat.
######################################
