name: Phantom-Waypoints
version: 1.2a
main: com.paralli.phantom_waypoints.Main
api-version: 1.18
author: aWildPhantom
commands:
  padmin:
    description: Pwaypoint admin command
    usage: /padmin <create | remove | reveal> <name>

permissions:
  pwaypoint.*:
    children:
      pwaypoint.admin: true
      pwaypoint.use: true
  pwaypoint.admin:
    description: Allows modification of Pwaypoints

  pwaypoint.use:
    description: Allows usage of the Pwaypoints


