name: Phantom-Waypoints
version: 1.1b
main: com.paralli.phantom_waypoints.Main
api-version: 1.18
author: aWildPhantom
commands:
  pwaypoint:
    description: Access the waypoint menu
    usages: "/pwaypoint <optional-either: tp | add> <optional: name>"